# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.models.deployment_public import DeploymentPublic

class TestDeploymentPublic(unittest.TestCase):
    """DeploymentPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentPublic:
        """Test DeploymentPublic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentPublic`
        """
        model = DeploymentPublic()
        if include_optional:
            return DeploymentPublic(
                environment_uuid = '',
                function_uuid = '',
                project_uuid = '',
                is_active = True,
                version_num = 56,
                notes = '',
                activated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                uuid = '',
                organization_uuid = '',
                function = lilypad.models.function_public.FunctionPublic(
                    project_uuid = '', 
                    version_num = 56, 
                    name = '0', 
                    signature = '', 
                    code = '', 
                    hash = '', 
                    dependencies = {
                        'key' : lilypad.models.dependency_info.DependencyInfo(
                            version = '', 
                            extras = [
                                ''
                                ], )
                        }, 
                    arg_types = {
                        'key' : ''
                        }, 
                    archived = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    custom_id = '', 
                    prompt_template = '', 
                    provider = '', 
                    model = '', 
                    call_params = lilypad.models.common_call_params.CommonCallParams(
                        temperature = 1.337, 
                        max_tokens = 56, 
                        top_p = 1.337, 
                        frequency_penalty = 1.337, 
                        presence_penalty = 1.337, 
                        seed = 56, 
                        stop = null, ), 
                    is_versioned = True, 
                    uuid = '', ),
                environment = lilypad.models.environment_public.EnvironmentPublic(
                    name = '', 
                    description = '', 
                    is_default = True, 
                    uuid = '', 
                    organization_uuid = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return DeploymentPublic(
                environment_uuid = '',
                function_uuid = '',
                uuid = '',
                organization_uuid = '',
        )
        """

    def testDeploymentPublic(self):
        """Test DeploymentPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
