# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_user(self) -> None:
        """Test case for user

        Get User
        """
        pass

    def test_user_active_organization_id(self) -> None:
        """Test case for user_active_organization_id

        Update User Active Organization Id
        """
        pass

    def test_user_keys(self) -> None:
        """Test case for user_keys

        Update User Keys
        """
        pass


if __name__ == '__main__':
    unittest.main()
