# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.models.span_public import SpanPublic

class TestSpanPublic(unittest.TestCase):
    """SpanPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpanPublic:
        """Test SpanPublic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpanPublic`
        """
        model = SpanPublic()
        if include_optional:
            return SpanPublic(
                span_id = '',
                function_uuid = '',
                type = 'function',
                cost = 1.337,
                scope = 'lilypad',
                input_tokens = 1.337,
                output_tokens = 1.337,
                duration_ms = 1.337,
                data = lilypad.models.data.Data(),
                parent_span_id = '',
                session_id = '',
                uuid = '',
                project_uuid = '',
                display_name = '',
                function = lilypad.models.function_public.FunctionPublic(
                    project_uuid = '', 
                    version_num = 56, 
                    name = '0', 
                    signature = '', 
                    code = '', 
                    hash = '', 
                    dependencies = {
                        'key' : lilypad.models.dependency_info.DependencyInfo(
                            version = '', 
                            extras = [
                                ''
                                ], )
                        }, 
                    arg_types = {
                        'key' : ''
                        }, 
                    archived = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    custom_id = '', 
                    prompt_template = '', 
                    provider = '', 
                    model = '', 
                    call_params = lilypad.models.common_call_params.CommonCallParams(
                        temperature = 1.337, 
                        max_tokens = 56, 
                        top_p = 1.337, 
                        frequency_penalty = 1.337, 
                        presence_penalty = 1.337, 
                        seed = 56, 
                        stop = null, ), 
                    is_versioned = True, 
                    uuid = '', ),
                annotations = [
                    lilypad.models.annotation_public.AnnotationPublic(
                        label = 'pass', 
                        reasoning = '', 
                        type = 'manual', 
                        data = lilypad.models.data.data(), 
                        assigned_to = '', 
                        uuid = '', 
                        project_uuid = '', 
                        span_uuid = '', 
                        function_uuid = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        span = lilypad.models.span_more_details.SpanMoreDetails(
                            uuid = '', 
                            project_uuid = '', 
                            function_uuid = '', 
                            display_name = '', 
                            provider = '', 
                            model = '', 
                            scope = 'lilypad', 
                            input_tokens = 1.337, 
                            output_tokens = 1.337, 
                            duration_ms = 1.337, 
                            signature = '', 
                            code = '', 
                            arg_values = lilypad.models.arg_values.arg_values(), 
                            output = '', 
                            messages = [
                                lilypad.models.message_param.MessageParam(
                                    role = '', 
                                    content = [
                                        null
                                        ], )
                                ], 
                            data = lilypad.models.data.Data(), 
                            cost = 1.337, 
                            template = '', 
                            status = '', 
                            events = [
                                lilypad.models.event.Event(
                                    name = '', 
                                    type = '', 
                                    message = '', 
                                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            tags = [
                                lilypad.models.tag_public.TagPublic(
                                    project_uuid = '', 
                                    name = '0', 
                                    uuid = '', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    organization_uuid = '', )
                                ], 
                            session_id = '', 
                            span_id = '', 
                            response = lilypad.models.response.response(), 
                            response_model = lilypad.models.response_model.response_model(), ), )
                    ],
                child_spans = [
                    lilypad.models.span_public.SpanPublic(
                        span_id = '', 
                        function_uuid = '', 
                        type = 'function', 
                        cost = 1.337, 
                        scope = 'lilypad', 
                        input_tokens = 1.337, 
                        output_tokens = 1.337, 
                        duration_ms = 1.337, 
                        data = lilypad.models.data.Data(), 
                        parent_span_id = '', 
                        session_id = '', 
                        uuid = '', 
                        project_uuid = '', 
                        display_name = '', 
                        function = lilypad.models.function_public.FunctionPublic(
                            project_uuid = '', 
                            version_num = 56, 
                            name = '0', 
                            signature = '', 
                            code = '', 
                            hash = '', 
                            dependencies = {
                                'key' : lilypad.models.dependency_info.DependencyInfo(
                                    version = '', 
                                    extras = [
                                        ''
                                        ], )
                                }, 
                            arg_types = {
                                'key' : ''
                                }, 
                            archived = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            custom_id = '', 
                            prompt_template = '', 
                            provider = '', 
                            model = '', 
                            call_params = lilypad.models.common_call_params.CommonCallParams(
                                temperature = 1.337, 
                                max_tokens = 56, 
                                top_p = 1.337, 
                                frequency_penalty = 1.337, 
                                presence_penalty = 1.337, 
                                seed = 56, 
                                stop = null, ), 
                            is_versioned = True, 
                            uuid = '', ), 
                        annotations = [
                            lilypad.models.annotation_public.AnnotationPublic(
                                label = 'pass', 
                                reasoning = '', 
                                data = lilypad.models.data.data(), 
                                assigned_to = '', 
                                uuid = '', 
                                project_uuid = '', 
                                span_uuid = '', 
                                function_uuid = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                span = lilypad.models.span_more_details.SpanMoreDetails(
                                    uuid = '', 
                                    project_uuid = '', 
                                    function_uuid = '', 
                                    display_name = '', 
                                    provider = '', 
                                    model = '', 
                                    scope = 'lilypad', 
                                    input_tokens = 1.337, 
                                    output_tokens = 1.337, 
                                    duration_ms = 1.337, 
                                    signature = '', 
                                    code = '', 
                                    arg_values = lilypad.models.arg_values.arg_values(), 
                                    output = '', 
                                    messages = [
                                        lilypad.models.message_param.MessageParam(
                                            role = '', 
                                            content = [
                                                null
                                                ], )
                                        ], 
                                    data = lilypad.models.data.Data(), 
                                    cost = 1.337, 
                                    template = '', 
                                    status = '', 
                                    events = [
                                        lilypad.models.event.Event(
                                            name = '', 
                                            type = '', 
                                            message = '', 
                                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                        ], 
                                    tags = [
                                        lilypad.models.tag_public.TagPublic(
                                            project_uuid = '', 
                                            name = '0', 
                                            uuid = '', 
                                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            organization_uuid = '', )
                                        ], 
                                    session_id = '', 
                                    span_id = '', 
                                    response = lilypad.models.response.response(), 
                                    response_model = lilypad.models.response_model.response_model(), ), )
                            ], 
                        child_spans = [
                            lilypad.models.span_public.SpanPublic(
                                span_id = '', 
                                function_uuid = '', 
                                cost = 1.337, 
                                scope = , 
                                input_tokens = 1.337, 
                                output_tokens = 1.337, 
                                duration_ms = 1.337, 
                                data = lilypad.models.data.Data(), 
                                parent_span_id = '', 
                                session_id = '', 
                                uuid = '', 
                                project_uuid = '', 
                                display_name = '', 
                                function = lilypad.models.function_public.FunctionPublic(
                                    project_uuid = '', 
                                    version_num = 56, 
                                    name = '0', 
                                    signature = '', 
                                    code = '', 
                                    hash = '', 
                                    dependencies = {
                                        'key' : lilypad.models.dependency_info.DependencyInfo(
                                            version = '', 
                                            extras = [
                                                ''
                                                ], )
                                        }, 
                                    arg_types = {
                                        'key' : ''
                                        }, 
                                    archived = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    custom_id = '', 
                                    prompt_template = '', 
                                    provider = '', 
                                    model = '', 
                                    is_versioned = True, 
                                    uuid = '', ), 
                                annotations = [
                                    lilypad.models.annotation_public.AnnotationPublic(
                                        reasoning = '', 
                                        data = lilypad.models.data.data(), 
                                        assigned_to = '', 
                                        uuid = '', 
                                        project_uuid = '', 
                                        span_uuid = '', 
                                        function_uuid = '', 
                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        span = lilypad.models.span_more_details.SpanMoreDetails(
                                            uuid = '', 
                                            project_uuid = '', 
                                            function_uuid = '', 
                                            display_name = '', 
                                            provider = '', 
                                            model = '', 
                                            scope = , 
                                            input_tokens = 1.337, 
                                            output_tokens = 1.337, 
                                            duration_ms = 1.337, 
                                            signature = '', 
                                            code = '', 
                                            arg_values = lilypad.models.arg_values.arg_values(), 
                                            output = '', 
                                            messages = [
                                                lilypad.models.message_param.MessageParam(
                                                    role = '', 
                                                    content = [
                                                        null
                                                        ], )
                                                ], 
                                            data = lilypad.models.data.Data(), 
                                            cost = 1.337, 
                                            template = '', 
                                            status = '', 
                                            session_id = '', 
                                            span_id = '', 
                                            response = lilypad.models.response.response(), 
                                            response_model = lilypad.models.response_model.response_model(), ), )
                                    ], 
                                child_spans = , 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                status = '', 
                                tags = [
                                    lilypad.models.tag_public.TagPublic(
                                        project_uuid = '', 
                                        name = '0', 
                                        uuid = '', 
                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        organization_uuid = '', )
                                    ], 
                                score = 1.337, )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = '', 
                        tags = [
                            
                            ], 
                        score = 1.337, )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = '',
                tags = [
                    lilypad.models.tag_public.TagPublic(
                        project_uuid = '', 
                        name = '0', 
                        uuid = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        organization_uuid = '', )
                    ],
                score = 1.337
            )
        else:
            return SpanPublic(
                span_id = '',
                scope = 'lilypad',
                uuid = '',
                project_uuid = '',
                function = lilypad.models.function_public.FunctionPublic(
                    project_uuid = '', 
                    version_num = 56, 
                    name = '0', 
                    signature = '', 
                    code = '', 
                    hash = '', 
                    dependencies = {
                        'key' : lilypad.models.dependency_info.DependencyInfo(
                            version = '', 
                            extras = [
                                ''
                                ], )
                        }, 
                    arg_types = {
                        'key' : ''
                        }, 
                    archived = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    custom_id = '', 
                    prompt_template = '', 
                    provider = '', 
                    model = '', 
                    call_params = lilypad.models.common_call_params.CommonCallParams(
                        temperature = 1.337, 
                        max_tokens = 56, 
                        top_p = 1.337, 
                        frequency_penalty = 1.337, 
                        presence_penalty = 1.337, 
                        seed = 56, 
                        stop = null, ), 
                    is_versioned = True, 
                    uuid = '', ),
                annotations = [
                    lilypad.models.annotation_public.AnnotationPublic(
                        label = 'pass', 
                        reasoning = '', 
                        type = 'manual', 
                        data = lilypad.models.data.data(), 
                        assigned_to = '', 
                        uuid = '', 
                        project_uuid = '', 
                        span_uuid = '', 
                        function_uuid = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        span = lilypad.models.span_more_details.SpanMoreDetails(
                            uuid = '', 
                            project_uuid = '', 
                            function_uuid = '', 
                            display_name = '', 
                            provider = '', 
                            model = '', 
                            scope = 'lilypad', 
                            input_tokens = 1.337, 
                            output_tokens = 1.337, 
                            duration_ms = 1.337, 
                            signature = '', 
                            code = '', 
                            arg_values = lilypad.models.arg_values.arg_values(), 
                            output = '', 
                            messages = [
                                lilypad.models.message_param.MessageParam(
                                    role = '', 
                                    content = [
                                        null
                                        ], )
                                ], 
                            data = lilypad.models.data.Data(), 
                            cost = 1.337, 
                            template = '', 
                            status = '', 
                            events = [
                                lilypad.models.event.Event(
                                    name = '', 
                                    type = '', 
                                    message = '', 
                                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            tags = [
                                lilypad.models.tag_public.TagPublic(
                                    project_uuid = '', 
                                    name = '0', 
                                    uuid = '', 
                                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    organization_uuid = '', )
                                ], 
                            session_id = '', 
                            span_id = '', 
                            response = lilypad.models.response.response(), 
                            response_model = lilypad.models.response_model.response_model(), ), )
                    ],
                child_spans = [
                    lilypad.models.span_public.SpanPublic(
                        span_id = '', 
                        function_uuid = '', 
                        type = 'function', 
                        cost = 1.337, 
                        scope = 'lilypad', 
                        input_tokens = 1.337, 
                        output_tokens = 1.337, 
                        duration_ms = 1.337, 
                        data = lilypad.models.data.Data(), 
                        parent_span_id = '', 
                        session_id = '', 
                        uuid = '', 
                        project_uuid = '', 
                        display_name = '', 
                        function = lilypad.models.function_public.FunctionPublic(
                            project_uuid = '', 
                            version_num = 56, 
                            name = '0', 
                            signature = '', 
                            code = '', 
                            hash = '', 
                            dependencies = {
                                'key' : lilypad.models.dependency_info.DependencyInfo(
                                    version = '', 
                                    extras = [
                                        ''
                                        ], )
                                }, 
                            arg_types = {
                                'key' : ''
                                }, 
                            archived = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            custom_id = '', 
                            prompt_template = '', 
                            provider = '', 
                            model = '', 
                            call_params = lilypad.models.common_call_params.CommonCallParams(
                                temperature = 1.337, 
                                max_tokens = 56, 
                                top_p = 1.337, 
                                frequency_penalty = 1.337, 
                                presence_penalty = 1.337, 
                                seed = 56, 
                                stop = null, ), 
                            is_versioned = True, 
                            uuid = '', ), 
                        annotations = [
                            lilypad.models.annotation_public.AnnotationPublic(
                                label = 'pass', 
                                reasoning = '', 
                                data = lilypad.models.data.data(), 
                                assigned_to = '', 
                                uuid = '', 
                                project_uuid = '', 
                                span_uuid = '', 
                                function_uuid = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                span = lilypad.models.span_more_details.SpanMoreDetails(
                                    uuid = '', 
                                    project_uuid = '', 
                                    function_uuid = '', 
                                    display_name = '', 
                                    provider = '', 
                                    model = '', 
                                    scope = 'lilypad', 
                                    input_tokens = 1.337, 
                                    output_tokens = 1.337, 
                                    duration_ms = 1.337, 
                                    signature = '', 
                                    code = '', 
                                    arg_values = lilypad.models.arg_values.arg_values(), 
                                    output = '', 
                                    messages = [
                                        lilypad.models.message_param.MessageParam(
                                            role = '', 
                                            content = [
                                                null
                                                ], )
                                        ], 
                                    data = lilypad.models.data.Data(), 
                                    cost = 1.337, 
                                    template = '', 
                                    status = '', 
                                    events = [
                                        lilypad.models.event.Event(
                                            name = '', 
                                            type = '', 
                                            message = '', 
                                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                        ], 
                                    tags = [
                                        lilypad.models.tag_public.TagPublic(
                                            project_uuid = '', 
                                            name = '0', 
                                            uuid = '', 
                                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            organization_uuid = '', )
                                        ], 
                                    session_id = '', 
                                    span_id = '', 
                                    response = lilypad.models.response.response(), 
                                    response_model = lilypad.models.response_model.response_model(), ), )
                            ], 
                        child_spans = [
                            lilypad.models.span_public.SpanPublic(
                                span_id = '', 
                                function_uuid = '', 
                                cost = 1.337, 
                                scope = , 
                                input_tokens = 1.337, 
                                output_tokens = 1.337, 
                                duration_ms = 1.337, 
                                data = lilypad.models.data.Data(), 
                                parent_span_id = '', 
                                session_id = '', 
                                uuid = '', 
                                project_uuid = '', 
                                display_name = '', 
                                function = lilypad.models.function_public.FunctionPublic(
                                    project_uuid = '', 
                                    version_num = 56, 
                                    name = '0', 
                                    signature = '', 
                                    code = '', 
                                    hash = '', 
                                    dependencies = {
                                        'key' : lilypad.models.dependency_info.DependencyInfo(
                                            version = '', 
                                            extras = [
                                                ''
                                                ], )
                                        }, 
                                    arg_types = {
                                        'key' : ''
                                        }, 
                                    archived = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    custom_id = '', 
                                    prompt_template = '', 
                                    provider = '', 
                                    model = '', 
                                    is_versioned = True, 
                                    uuid = '', ), 
                                annotations = [
                                    lilypad.models.annotation_public.AnnotationPublic(
                                        reasoning = '', 
                                        data = lilypad.models.data.data(), 
                                        assigned_to = '', 
                                        uuid = '', 
                                        project_uuid = '', 
                                        span_uuid = '', 
                                        function_uuid = '', 
                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        span = lilypad.models.span_more_details.SpanMoreDetails(
                                            uuid = '', 
                                            project_uuid = '', 
                                            function_uuid = '', 
                                            display_name = '', 
                                            provider = '', 
                                            model = '', 
                                            scope = , 
                                            input_tokens = 1.337, 
                                            output_tokens = 1.337, 
                                            duration_ms = 1.337, 
                                            signature = '', 
                                            code = '', 
                                            arg_values = lilypad.models.arg_values.arg_values(), 
                                            output = '', 
                                            messages = [
                                                lilypad.models.message_param.MessageParam(
                                                    role = '', 
                                                    content = [
                                                        null
                                                        ], )
                                                ], 
                                            data = lilypad.models.data.Data(), 
                                            cost = 1.337, 
                                            template = '', 
                                            status = '', 
                                            session_id = '', 
                                            span_id = '', 
                                            response = lilypad.models.response.response(), 
                                            response_model = lilypad.models.response_model.response_model(), ), )
                                    ], 
                                child_spans = , 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                status = '', 
                                tags = [
                                    lilypad.models.tag_public.TagPublic(
                                        project_uuid = '', 
                                        name = '0', 
                                        uuid = '', 
                                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        organization_uuid = '', )
                                    ], 
                                score = 1.337, )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = '', 
                        tags = [
                            
                            ], 
                        score = 1.337, )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tags = [
                    lilypad.models.tag_public.TagPublic(
                        project_uuid = '', 
                        name = '0', 
                        uuid = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        organization_uuid = '', )
                    ],
        )
        """

    def testSpanPublic(self):
        """Test SpanPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
