# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.models.image_part import ImagePart

class TestImagePart(unittest.TestCase):
    """ImagePart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImagePart:
        """Test ImagePart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImagePart`
        """
        model = ImagePart()
        if include_optional:
            return ImagePart(
                type = 'image',
                media_type = '',
                image = '',
                detail = ''
            )
        else:
            return ImagePart(
                type = 'image',
                media_type = '',
                image = '',
                detail = '',
        )
        """

    def testImagePart(self):
        """Test ImagePart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
