# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.api.google_api import GoogleApi


class TestGoogleApi(unittest.TestCase):
    """GoogleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GoogleApi()

    def tearDown(self) -> None:
        pass

    def test_callback(self) -> None:
        """Test case for callback

        Google Callback
        """
        pass


if __name__ == '__main__':
    unittest.main()
