# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_project(self) -> None:
        """Test case for project

        Create Project
        """
        pass

    def test_project_0(self) -> None:
        """Test case for project_0

        Get Project
        """
        pass

    def test_project_1(self) -> None:
        """Test case for project_1

        Delete Project
        """
        pass

    def test_project_2(self) -> None:
        """Test case for project_2

        Patch Project
        """
        pass

    def test_projects(self) -> None:
        """Test case for projects

        Get Projects
        """
        pass


if __name__ == '__main__':
    unittest.main()
