# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.api.external_api_keys_api import ExternalAPIKeysApi


class TestExternalAPIKeysApi(unittest.TestCase):
    """ExternalAPIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExternalAPIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_external_api_key(self) -> None:
        """Test case for external_api_key

        Store External Api Key
        """
        pass

    def test_external_api_key_0(self) -> None:
        """Test case for external_api_key_0

        Get External Api Key
        """
        pass

    def test_external_api_key_1(self) -> None:
        """Test case for external_api_key_1

        Delete External Api Key
        """
        pass

    def test_external_api_key_2(self) -> None:
        """Test case for external_api_key_2

        Update External Api Key
        """
        pass

    def test_external_api_keys(self) -> None:
        """Test case for external_api_keys

        List External Api Keys
        """
        pass


if __name__ == '__main__':
    unittest.main()
