# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.models.annotation_create import AnnotationCreate

class TestAnnotationCreate(unittest.TestCase):
    """AnnotationCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotationCreate:
        """Test AnnotationCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotationCreate`
        """
        model = AnnotationCreate()
        if include_optional:
            return AnnotationCreate(
                span_uuid = '',
                project_uuid = '',
                function_uuid = '',
                label = 'pass',
                reasoning = '',
                type = 'manual',
                data = None,
                assigned_to = [
                    ''
                    ],
                assignee_email = [
                    ''
                    ]
            )
        else:
            return AnnotationCreate(
        )
        """

    def testAnnotationCreate(self):
        """Test AnnotationCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
