# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_tag(self) -> None:
        """Test case for tag

        Create Tag
        """
        pass

    def test_tag_0(self) -> None:
        """Test case for tag_0

        Get Tag
        """
        pass

    def test_tag_1(self) -> None:
        """Test case for tag_1

        Delete Tag
        """
        pass

    def test_tag_2(self) -> None:
        """Test case for tag_2

        Patch Tag
        """
        pass

    def test_tags(self) -> None:
        """Test case for tags

        Get Tags
        """
        pass

    def test_tags_by_project(self) -> None:
        """Test case for tags_by_project

        Get Tags By Project
        """
        pass


if __name__ == '__main__':
    unittest.main()
