# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.api.organization_invites_api import OrganizationInvitesApi


class TestOrganizationInvitesApi(unittest.TestCase):
    """OrganizationInvitesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationInvitesApi()

    def tearDown(self) -> None:
        pass

    def test_organization_invite(self) -> None:
        """Test case for organization_invite

        Get Organization Invite
        """
        pass

    def test_organization_invite_0(self) -> None:
        """Test case for organization_invite_0

        Create Organization Invite
        """
        pass

    def test_organization_invite_1(self) -> None:
        """Test case for organization_invite_1

        Remove Organization Invite
        """
        pass

    def test_organization_invites(self) -> None:
        """Test case for organization_invites

        Get Organization Invites
        """
        pass


if __name__ == '__main__':
    unittest.main()
