# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lilypad.api.functions_api import FunctionsApi


class TestFunctionsApi(unittest.TestCase):
    """FunctionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FunctionsApi()

    def tearDown(self) -> None:
        pass

    def test_deployed_function_by_names(self) -> None:
        """Test case for deployed_function_by_names

        Get Deployed Function By Names
        """
        pass

    def test_function(self) -> None:
        """Test case for function

        Get Function
        """
        pass

    def test_function_0(self) -> None:
        """Test case for function_0

        Archive Function
        """
        pass

    def test_function_1(self) -> None:
        """Test case for function_1

        Update Function
        """
        pass

    def test_function_by_hash(self) -> None:
        """Test case for function_by_hash

        Get Function By Hash
        """
        pass

    def test_function_by_version(self) -> None:
        """Test case for function_by_version

        Get Function By Version
        """
        pass

    def test_functions(self) -> None:
        """Test case for functions

        Get Functions
        """
        pass

    def test_functions_by_name(self) -> None:
        """Test case for functions_by_name

        Get Functions By Name
        """
        pass

    def test_functions_by_name_0(self) -> None:
        """Test case for functions_by_name_0

        Archive Functions By Name
        """
        pass

    def test_latest_version_unique_function_names(self) -> None:
        """Test case for latest_version_unique_function_names

        Get Latest Version Unique Function Names
        """
        pass

    def test_new_function(self) -> None:
        """Test case for new_function

        Create New Function
        """
        pass

    def test_playground(self) -> None:
        """Test case for playground

        Run Function in Playground
        """
        pass

    def test_unique_function_names(self) -> None:
        """Test case for unique_function_names

        Get Unique Function Names
        """
        pass

    def test_versioned_function(self) -> None:
        """Test case for versioned_function

        Create Versioned Function
        """
        pass


if __name__ == '__main__':
    unittest.main()
