/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as ProjectsProjectIdImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsImport } from './routes/projects_/$projectId.llm-fns_.$llmFunctionId.fn-params'

// Create Virtual Routes

const DiffLazyImport = createFileRoute('/diff')()

// Create/Update Routes

const DiffLazyRoute = DiffLazyImport.update({
  path: '/diff',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/diff.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdRoute = ProjectsProjectIdImport.update({
  path: '/projects/$projectId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute =
  ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsImport.update({
    path: '/projects/$projectId/llm-fns/$llmFunctionId/fn-params',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/llm-fns/$llmFunctionId/fn-params': {
      id: '/projects/$projectId/llm-fns/$llmFunctionId/fn-params'
      path: '/projects/$projectId/llm-fns/$llmFunctionId/fn-params'
      fullPath: '/projects/$projectId/llm-fns/$llmFunctionId/fn-params'
      preLoaderRoute: typeof ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff': typeof DiffLazyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/llm-fns/$llmFunctionId/fn-params': typeof ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff': typeof DiffLazyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/llm-fns/$llmFunctionId/fn-params': typeof ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/diff': typeof DiffLazyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/llm-fns/$llmFunctionId/fn-params': typeof ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diff'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/llm-fns/$llmFunctionId/fn-params'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diff'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/llm-fns/$llmFunctionId/fn-params'
  id:
    | '__root__'
    | '/'
    | '/diff'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/llm-fns/$llmFunctionId/fn-params'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffLazyRoute: typeof DiffLazyRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute: typeof ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffLazyRoute: DiffLazyRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute:
    ProjectsProjectIdLlmFnsLlmFunctionIdFnParamsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/diff",
        "/projects/$projectId",
        "/projects/",
        "/projects/$projectId/llm-fns/$llmFunctionId/fn-params"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/diff": {
      "filePath": "diff.lazy.tsx"
    },
    "/projects/$projectId": {
      "filePath": "projects/$projectId.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    },
    "/projects/$projectId/llm-fns/$llmFunctionId/fn-params": {
      "filePath": "projects_/$projectId.llm-fns_.$llmFunctionId.fn-params.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
