/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects.index'
import { Route as ProjectsProjectIdImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdTracesImport } from './routes/projects.$projectId.traces'
import { Route as ProjectsProjectIdFunctionsIndexImport } from './routes/projects.$projectId.functions.index'
import { Route as ProjectsProjectIdFunctionsFunctionNameImport } from './routes/projects.$projectId.functions.$functionName'
import { Route as ProjectsProjectIdFunctionsFunctionNameIndexImport } from './routes/projects.$projectId.functions.$functionName.index'
import { Route as ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdImport } from './routes/projects.$projectId.functions.$functionName.versions.$versionId'

// Create Virtual Routes

const DiffLazyImport = createFileRoute('/diff')()

// Create/Update Routes

const DiffLazyRoute = DiffLazyImport.update({
  path: '/diff',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/diff.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdRoute = ProjectsProjectIdImport.update({
  path: '/projects/$projectId',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdTracesRoute = ProjectsProjectIdTracesImport.update({
  path: '/traces',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

const ProjectsProjectIdFunctionsIndexRoute =
  ProjectsProjectIdFunctionsIndexImport.update({
    path: '/functions/',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

const ProjectsProjectIdFunctionsFunctionNameRoute =
  ProjectsProjectIdFunctionsFunctionNameImport.update({
    path: '/functions/$functionName',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

const ProjectsProjectIdFunctionsFunctionNameIndexRoute =
  ProjectsProjectIdFunctionsFunctionNameIndexImport.update({
    path: '/',
    getParentRoute: () => ProjectsProjectIdFunctionsFunctionNameRoute,
  } as any)

const ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute =
  ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdImport.update({
    path: '/versions/$versionId',
    getParentRoute: () => ProjectsProjectIdFunctionsFunctionNameRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/traces': {
      id: '/projects/$projectId/traces'
      path: '/traces'
      fullPath: '/projects/$projectId/traces'
      preLoaderRoute: typeof ProjectsProjectIdTracesImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/functions/$functionName': {
      id: '/projects/$projectId/functions/$functionName'
      path: '/functions/$functionName'
      fullPath: '/projects/$projectId/functions/$functionName'
      preLoaderRoute: typeof ProjectsProjectIdFunctionsFunctionNameImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/functions/': {
      id: '/projects/$projectId/functions/'
      path: '/functions'
      fullPath: '/projects/$projectId/functions'
      preLoaderRoute: typeof ProjectsProjectIdFunctionsIndexImport
      parentRoute: typeof ProjectsProjectIdImport
    }
    '/projects/$projectId/functions/$functionName/': {
      id: '/projects/$projectId/functions/$functionName/'
      path: '/'
      fullPath: '/projects/$projectId/functions/$functionName/'
      preLoaderRoute: typeof ProjectsProjectIdFunctionsFunctionNameIndexImport
      parentRoute: typeof ProjectsProjectIdFunctionsFunctionNameImport
    }
    '/projects/$projectId/functions/$functionName/versions/$versionId': {
      id: '/projects/$projectId/functions/$functionName/versions/$versionId'
      path: '/versions/$versionId'
      fullPath: '/projects/$projectId/functions/$functionName/versions/$versionId'
      preLoaderRoute: typeof ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdImport
      parentRoute: typeof ProjectsProjectIdFunctionsFunctionNameImport
    }
  }
}

// Create and export the route tree

interface ProjectsProjectIdFunctionsFunctionNameRouteChildren {
  ProjectsProjectIdFunctionsFunctionNameIndexRoute: typeof ProjectsProjectIdFunctionsFunctionNameIndexRoute
  ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute: typeof ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute
}

const ProjectsProjectIdFunctionsFunctionNameRouteChildren: ProjectsProjectIdFunctionsFunctionNameRouteChildren =
  {
    ProjectsProjectIdFunctionsFunctionNameIndexRoute:
      ProjectsProjectIdFunctionsFunctionNameIndexRoute,
    ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute:
      ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute,
  }

const ProjectsProjectIdFunctionsFunctionNameRouteWithChildren =
  ProjectsProjectIdFunctionsFunctionNameRoute._addFileChildren(
    ProjectsProjectIdFunctionsFunctionNameRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdTracesRoute: typeof ProjectsProjectIdTracesRoute
  ProjectsProjectIdFunctionsFunctionNameRoute: typeof ProjectsProjectIdFunctionsFunctionNameRouteWithChildren
  ProjectsProjectIdFunctionsIndexRoute: typeof ProjectsProjectIdFunctionsIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdTracesRoute: ProjectsProjectIdTracesRoute,
  ProjectsProjectIdFunctionsFunctionNameRoute:
    ProjectsProjectIdFunctionsFunctionNameRouteWithChildren,
  ProjectsProjectIdFunctionsIndexRoute: ProjectsProjectIdFunctionsIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diff': typeof DiffLazyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/traces': typeof ProjectsProjectIdTracesRoute
  '/projects/$projectId/functions/$functionName': typeof ProjectsProjectIdFunctionsFunctionNameRouteWithChildren
  '/projects/$projectId/functions': typeof ProjectsProjectIdFunctionsIndexRoute
  '/projects/$projectId/functions/$functionName/': typeof ProjectsProjectIdFunctionsFunctionNameIndexRoute
  '/projects/$projectId/functions/$functionName/versions/$versionId': typeof ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diff': typeof DiffLazyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/traces': typeof ProjectsProjectIdTracesRoute
  '/projects/$projectId/functions': typeof ProjectsProjectIdFunctionsIndexRoute
  '/projects/$projectId/functions/$functionName': typeof ProjectsProjectIdFunctionsFunctionNameIndexRoute
  '/projects/$projectId/functions/$functionName/versions/$versionId': typeof ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/diff': typeof DiffLazyRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/traces': typeof ProjectsProjectIdTracesRoute
  '/projects/$projectId/functions/$functionName': typeof ProjectsProjectIdFunctionsFunctionNameRouteWithChildren
  '/projects/$projectId/functions/': typeof ProjectsProjectIdFunctionsIndexRoute
  '/projects/$projectId/functions/$functionName/': typeof ProjectsProjectIdFunctionsFunctionNameIndexRoute
  '/projects/$projectId/functions/$functionName/versions/$versionId': typeof ProjectsProjectIdFunctionsFunctionNameVersionsVersionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diff'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/traces'
    | '/projects/$projectId/functions/$functionName'
    | '/projects/$projectId/functions'
    | '/projects/$projectId/functions/$functionName/'
    | '/projects/$projectId/functions/$functionName/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diff'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/traces'
    | '/projects/$projectId/functions'
    | '/projects/$projectId/functions/$functionName'
    | '/projects/$projectId/functions/$functionName/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/diff'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/traces'
    | '/projects/$projectId/functions/$functionName'
    | '/projects/$projectId/functions/'
    | '/projects/$projectId/functions/$functionName/'
    | '/projects/$projectId/functions/$functionName/versions/$versionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiffLazyRoute: typeof DiffLazyRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiffLazyRoute: DiffLazyRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/diff",
        "/projects/$projectId",
        "/projects/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/diff": {
      "filePath": "diff.lazy.tsx"
    },
    "/projects/$projectId": {
      "filePath": "projects.$projectId.tsx",
      "children": [
        "/projects/$projectId/traces",
        "/projects/$projectId/functions/$functionName",
        "/projects/$projectId/functions/"
      ]
    },
    "/projects/": {
      "filePath": "projects.index.tsx"
    },
    "/projects/$projectId/traces": {
      "filePath": "projects.$projectId.traces.tsx",
      "parent": "/projects/$projectId"
    },
    "/projects/$projectId/functions/$functionName": {
      "filePath": "projects.$projectId.functions.$functionName.tsx",
      "parent": "/projects/$projectId",
      "children": [
        "/projects/$projectId/functions/$functionName/",
        "/projects/$projectId/functions/$functionName/versions/$versionId"
      ]
    },
    "/projects/$projectId/functions/": {
      "filePath": "projects.$projectId.functions.index.tsx",
      "parent": "/projects/$projectId"
    },
    "/projects/$projectId/functions/$functionName/": {
      "filePath": "projects.$projectId.functions.$functionName.index.tsx",
      "parent": "/projects/$projectId/functions/$functionName"
    },
    "/projects/$projectId/functions/$functionName/versions/$versionId": {
      "filePath": "projects.$projectId.functions.$functionName.versions.$versionId.tsx",
      "parent": "/projects/$projectId/functions/$functionName"
    }
  }
}
ROUTE_MANIFEST_END */
