"""Add exernal_api_keys table

Revision ID: 0023
Revises: 0022
Create Date: 2025-03-20 00:04:51.753432

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_api_keys",
        sa.Column("service_name", AutoString(), nullable=False),
        sa.Column("secret_id", AutoString(), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
            name=op.f("external_api_keys_user_id_users_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("external_api_keys_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("external_api_keys")
    # ### end Alembic commands ###
