"""tags created by

Revision ID: 0031
Revises: 0030
Create Date: 2025-04-07 16:22:20.538451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0031"
down_revision: str | None = "0030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("span_tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.Uuid(), nullable=False))
        batch_op.create_index(
            batch_op.f("span_tags_created_by_idx"), ["created_by"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("span_tags_created_by_users_fkey"),
            "users",
            ["created_by"],
            ["uuid"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("span_tags", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("span_tags_created_by_users_fkey"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("span_tags_created_by_idx"))
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
