"""add function environment link

Revision ID: 0045
Revises: 0044
Create Date: 2025-07-02 09:15:14.895074

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0045"
down_revision: str | None = "0044"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "function_environments",
        sa.Column("function_uuid", sa.Uuid(), nullable=False),
        sa.Column("environment_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_uuid"],
            ["environments.uuid"],
            name=op.f("function_environments_environment_uuid_environments_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["function_uuid"],
            ["functions.uuid"],
            name=op.f("function_environments_function_uuid_functions_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "function_uuid", "environment_uuid", name=op.f("function_environments_pkey")
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("function_environments")
    # ### end Alembic commands ###
