[test]
preload = ["./tests/setup-db.ts"]
coverage = true
coverageSkipTestFiles = true
coverageThreshold = { lines = 1, functions = 1, statements = 1 }
# Ignores until we achieve 100% coverage in following PRs
coveragePathIgnorePatterns = [
    "tests/**",
    "**/*.test.ts",
    "**/*.spec.ts",
    "db/schema/*.ts",
    "src/**",
    "worker/**",
]
