[test]
preload = ["./tests/setup.ts"]
coverage = true
coverageSkipTestFiles = false
coverageThreshold = { lines = 1, functions = 1, statements = 1 }
# Ignores until we achieve 100% coverage in following PRs
coveragePathIgnorePatterns = [
    "tests/setup.ts",
    "db/schema/*.ts",
    "src/**",
    "worker/**",
]
