name = "lilypad"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
main = "worker/index.ts"
route = { pattern = "v1.lilypad.mirascope.com/*", zone_name = "mirascope.com" }

[vars]
SITE_URL = "https://lilypad.mirascope.com"
GITHUB_CLIENT_ID = "Ov23liUXN3zH9UbkKZqr"
GITHUB_CALLBACK_URL = "https://lilypad.mirascope.com/auth/github/callback"
GOOGLE_CLIENT_ID = "454509490482-jp8vn2vq01qtce96cavt4bgqsn9e1j7n.apps.googleusercontent.com"
GOOGLE_CALLBACK_URL = "https://lilypad.mirascope.com/auth/google/callback"

[assets]
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/auth/*"]

[observability]
enabled = true

[triggers]
crons = ["0 0 * * 7"]
