# This file was auto-generated by Fern from our API Definition.

import enum


class LilypadEnvironment(enum.Enum):
    PRODUCTION = "https://v1.lilypad.mirascope.com"
    STAGING = "https://staging.lilypad.mirascope.com"
    LOCAL = "http://localhost:3000"
