blank_issues_enabled: true
contact_links:
  - name: 💬 Join Slack
    url: "https://mirascope.com/discord-invite"
    about: Join the Mirascope Discord to ask questions, get help and chat about Lilypad
