name: 💡 Feature Request
description: Suggest a feature or new functionality for Lillypad
labels: [enhancement]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us what you're thinking...

    validations:
      required: true
