services:
  postgres:
    image: supabase/postgres:15.8.1.060
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  lilypad:
    image: lilypad
    ports:
      - "8000:8000"
    environment:
      - LILYPAD_DB_HOST=postgres
      - LILYPAD_DB_NAME=postgres
      - LILYPAD_DB_PASSWORD=password
      - LILYPAD_DB_PORT=5432
      - LILYPAD_DB_USER=supabase_admin
      - LILYPAD_GITHUB_CLIENT_ID=...
      - LILYPAD_GITHUB_CLIENT_SECRET=...
      - LILYPAD_GOOGLE_CLIENT_ID=...
      - LILYPAD_GOOGLE_CLIENT_SECRET=...
      - LILYPAD_JWT_SECRET=...
      - LILYPAD_SERVE_FRONTEND=true
      - LILYPAD_REMOTE_API_URL=http://localhost:8000
      - LILYPAD_REMOTE_CLIENT_URL=http://localhost:8000
      - LILYPAD_PLAYGROUND_VENV_PATH=/opt/playground-venv
      - LILYPAD_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - LILYPAD_KAFKA_TOPIC_SPAN_INGESTION=span-ingestion
      - LILYPAD_KAFKA_CONSUMER_GROUP=lilypad-span-processor
      - LILYPAD_KAFKA_MAX_CONCURRENT_TRACES=1000
      - LILYPAD_KAFKA_MAX_SPANS_PER_TRACE=500
      - LILYPAD_KAFKA_BUFFER_TTL_SECONDS=300
    depends_on:
      - postgres
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/data
      - zookeeper-logs:/datalog
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_RETENTION_HOURS: 168  # 7 days
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:29092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres-data:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
