"""Table names for the database models."""

PROJECT_TABLE_NAME = "projects"
SPAN_TABLE_NAME = "spans"
FUNCTION_TABLE_NAME = "functions"
USER_TABLE_NAME = "users"
ORGANIZATION_TABLE_NAME = "organizations"
USER_ORGANIZATION_TABLE_NAME = "user_organizations"
API_KEY_TABLE_NAME = "api_keys"
ANNOTATION_TABLE_NAME = "annotations"
ORGANIZATION_INVITE_TABLE_NAME = "organization_invites"
ENVIRONMENT_TABLE_NAME = "environments"
DEPLOYMENT_TABLE_NAME = "deployments"
EXTERNAL_API_KEY_TABLE_NAME = "external_api_keys"
USER_CONSENT_TABLE_NAME = "user_consents"
TAG_TABLE_NAME = "tags"
SPAN_TAG_LINK_TABLE_NAME = "span_tags"
EXPERIMENT_DEFINITION_TABLE_NAME = "experiment_definitions"
EXPERIMENT_RUN_TABLE_NAME = "experiment_runs"
SAMPLE_RESULT_TABLE_NAME = "sample_results"
