"""Add FunctionTagLink

Revision ID: 0033
Revises: 0032
Create Date: 2025-04-14 17:28:02.356753

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0033"
down_revision: str | None = "0032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "function_tags",
        sa.Column("function_uuid", sa.Uuid(), nullable=False),
        sa.Column("tag_uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["function_uuid"],
            ["functions.uuid"],
            name=op.f("function_tags_function_uuid_functions_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_uuid"], ["tags.uuid"], name=op.f("function_tags_tag_uuid_tags_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "function_uuid", "tag_uuid", name=op.f("function_tags_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("function_tags")
    # ### end Alembic commands ###
