"""update span type

Revision ID: 0038
Revises: 0037
Create Date: 2025-05-18 12:48:07.353152

"""

from collections.abc import Sequence

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "0038"
down_revision: str | None = "0037"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="spantype",
        new_values=["FUNCTION", "TRACE", "MIRASCOPE_V1"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="spans", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore[attr-defined]
        enum_schema="public",
        enum_name="spantype",
        new_values=["FUNCTION", "TRACE"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="spans", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
