# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .tier import Tier


class LicenseInfo(UncheckedBaseModel):
    """
    Pydantic model for license validation
    """

    customer: str
    license_id: str
    expires_at: dt.datetime
    tier: Tier
    organization_uuid: typing.Optional[str] = None
    is_expired: bool = pydantic.Field()
    """
    Check if the license has expired
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
