# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UserConsentUpdate(BaseModel):
    """
    UserConsent update model.
    """ # noqa: E501
    privacy_policy_version: Optional[StrictStr] = None
    privacy_policy_accepted_at: Optional[datetime] = None
    tos_version: Optional[StrictStr] = None
    tos_accepted_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["privacy_policy_version", "privacy_policy_accepted_at", "tos_version", "tos_accepted_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserConsentUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if privacy_policy_version (nullable) is None
        # and model_fields_set contains the field
        if self.privacy_policy_version is None and "privacy_policy_version" in self.model_fields_set:
            _dict['privacy_policy_version'] = None

        # set to None if privacy_policy_accepted_at (nullable) is None
        # and model_fields_set contains the field
        if self.privacy_policy_accepted_at is None and "privacy_policy_accepted_at" in self.model_fields_set:
            _dict['privacy_policy_accepted_at'] = None

        # set to None if tos_version (nullable) is None
        # and model_fields_set contains the field
        if self.tos_version is None and "tos_version" in self.model_fields_set:
            _dict['tos_version'] = None

        # set to None if tos_accepted_at (nullable) is None
        # and model_fields_set contains the field
        if self.tos_accepted_at is None and "tos_accepted_at" in self.model_fields_set:
            _dict['tos_accepted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserConsentUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "privacy_policy_version": obj.get("privacy_policy_version"),
            "privacy_policy_accepted_at": obj.get("privacy_policy_accepted_at"),
            "tos_version": obj.get("tos_version"),
            "tos_accepted_at": obj.get("tos_accepted_at")
        })
        return _obj


