"""better span table

Revision ID: 0013
Revises: 0012
Create Date: 2025-02-21 15:26:33.622026

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("input_tokens", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("output_tokens", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("duration_ms", sa.Float(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("spans_parent_span_id_spans_fkey"),
            "spans",
            ["parent_span_id"],
            ["span_id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("spans_parent_span_id_spans_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("duration_ms")
        batch_op.drop_column("output_tokens")
        batch_op.drop_column("input_tokens")

    # ### end Alembic commands ###
