# This file was auto-generated by Fern from our API Definition.

import typing

PlaygroundErrorType = typing.Union[
    typing.Literal[
        "TimeoutError",
        "ConfigurationError",
        "SubprocessError",
        "OutputParsingError",
        "OutputMarkerError",
        "InternalPlaygroundError",
        "ExecutionError",
        "BadRequestError",
        "NotFoundError",
        "InvalidInputError",
        "ApiKeyIssue",
        "UnexpectedServerError",
    ],
    typing.Any,
]
