name: Build Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd app/client
          rm -rf node_modules bun.lock
          bun install

      - name: Run typecheck
        run: |
          cd app/client
          bun typecheck

      - name: Run tests
        run: |
          cd app/client
          bun test --reporter=junit --reporter-outfile=./test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: app/client/test-results.xml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            app/client/test-results.xml
          check_name: Client Test Results
          comment_mode: failures
