name: lint
run-name: ${{ github.actor }} is linting the package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lints:
    name: Ruff, Pyright, and Codespell
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/python

    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: '*.lock,./app/client/pnpm-lock.yaml,./docs/pnpm-lock.yaml,./playground-requirements.lock'

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.6.12/install.sh | sh

      - name: Set Up Python Environment
        run: uv python install 3.11


      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Ruff
        run: uv run ruff check .

      - name: Run Pyright
        run: uv run pyright .

      - name: Minimize uv cache
        run: uv cache prune --ci
