name: release
run-name: ${{ github.actor }} is releasing ${{ github.ref_name }}

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-app:
    name: App Release (currently no-op) - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: App release placeholder
        run: |
          echo "App release for tag: ${{ github.ref_name }}"
          echo "No action required for app release"

  release-python:
    name: Python SDK Release - ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.7.8/install.sh | sh

      - name: Set up Python
        run: uv python install 3.10

      - name: Change to Python directory
        run: cd sdks/python

      - name: Build Package
        working-directory: ./sdks/python
        run: uv build

      - name: Publish Python Package
        working-directory: ./sdks/python
        run: uv publish
