name: test
run-name: ${{ github.actor }} is testing the package

on:
  push:
    branches: [v1]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    services:
      postgres:
        image: paradedb/paradedb:latest
        env:
          POSTGRES_DB: lilypad_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    env:
      TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/lilypad_test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install package dependencies
        run: bun install

      - name: Run tests
        run: bun test
