name: TypeScript SDK Lint

on:
  push:
    branches: [main, v1]
    paths:
      - 'sdks/typescript/**'
      - '.github/workflows/typescript-sdk-lint.yml'
  pull_request:
    paths:
      - 'sdks/typescript/**'
      - '.github/workflows/typescript-sdk-lint.yml'

jobs:
  lint-typescript:
    name: Lint TypeScript SDK
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdks/typescript

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: sdks/typescript/node_modules
          key: ${{ runner.os }}-typescript-sdk-${{ hashFiles('sdks/typescript/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-typescript-sdk-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run typecheck

      - name: Run Prettier format check
        run: npm run format:check
